services: 
  java_app: 
    container_name: java_app
    image: crud-java:1.0 
    build: .
    ports: 
      - 8090:8090
    depends_on: 
      - java_db 
  java_db: 
    container_name: java_db 
    image: postgres:latest 
    ports: 
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=proyectos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


      